_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
lambda1:
    value: 0.001
lambda2:
    value: 0.005
learning_rate:
    value: 0.03
mu:
    value: 0.1
s:
    value: 1
tau:
    value: 0.0001
